#!/bin/bash
#
#       /etc/rc.d/init.d/cookied
# cookied  This shell script takes care of starting and stopping
#               cookieDaemon (the IGSPnet cookie daemon)
#
# Author: Rob Wagner
#
# chkconfig: 35 20 80
# description: cookieDaemon is the service that connects to IGSPnet \
# and is used by verifyCookie to communicate with Oracle.
#
# known bug: hangs ssh on exit (https://bugzilla.mindrot.org/show_bug.cgi?id=52)

# Source function library.
. /etc/init.d/functions

COOKIEDAEMON_DIR="/u01/db/oracle/product/10.2.0/db_1/admin/test1/scripts"

start() {
        echo -n "Starting IGSPnet cookieDaemon test instance: "
        PID=`pgrep -f cookieDaemonTest`
        if [[ ! -z $PID ]]; then
                echo cookieDaemon test instance already running: $PID
                exit 2;
        else
		cd $COOKIEDAEMON_DIR
                if [ ! -e "$COOKIEDAEMON_DIR/cookieDaemon" ]; then
                   echo cookieDaemon not found
                   exit 2;
                fi
                DAEMON_USER=`ls -l "$COOKIEDAEMON_DIR/cookieDaemon" | awk '{print $3;}'`
                export LD_LIBRARY_PATH=/u01/db/oracle/product/10.2.0/db_1/lib
                export ORACLE_HOME=/u01/db/oracle/product/10.2.0/db_1
		daemon --user=$DAEMON_USER "$COOKIEDAEMON_DIR/cookieDaemonTest &"
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cookieDaemonTest
                return $RETVAL
        fi

}

stop() {
        echo -n "Shutting down IGSPnet cookieDaemon test instance: "
        echo
        killproc cookieDaemonTest
        echo
        rm -f /var/lock/subsys/cookieDaemonTest
        return 0
}

status() {
        if [ -e /var/lock/subsys/cookieDaemonTest ]
                then 
			echo "IGSPnet cookieDaemon test instance is running."
                else 
			echo "IGSPnet cookieDaemon test instance is not running."
        fi 
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
   status)
        status
        ;;
    *)
        echo "Usage:  {start|stop|restart|status}"
        exit 1
        ;;
esac
exit $?

